import './globals.css'
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UN-CampusConnect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body style={{
        backgroundColor: 'rgba(243, 244,   246, 1)', className: inter.className}}>{children}</body>
    </html>
  )
}
