import './globals.css'
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
import { Navigation } from './components/Navigation';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UN-CampusConnect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <Head>
        <meta charset="utf-8" />
        <meta className="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      </Head>
      <body className={`${inter.className} `} >
        {children}
      </body>
    </html>
  )
}
